language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm build
- npm test
deploy:
  provider: heroku
  app: dindin-vieu
  api_key:
    secure: gs4FOmB1k/wZ8m18WPhI4IDb3zY7O5nL6vUO2ufgLnu6h3rmEiZZ6WP1mbmM5CeLNIfhwx+n7whIPEI+VK8p2AlzUW2ffGh4aGlI6vojirWQeAwPHf6HmOjOEUEXi78xG7/VvNP0vNHDfloGBypNhYSMi9fFvzljUHKEgmz0bmpK6J+g4oYs5fr3JMnk6jbFx2gVZoAHhjzeUrIV2yyye0pRhg8XgXPnzPcsL16taB4HaFHlRr4UUYh1wxuL+dhwyiLDWbK85A6g86N2tfsqaQ6sBL53W6K9zA1JL7cFIQOWzTc7WzCLV8J643VI9Pw5uuOuEaC8XjChdLUr6Pdrizem1RDOfXTK+WCLNQk48CYXcJXCEZkzCeZqqS6PLWaVJseD1Pp0Go2v7JpFy17soMjSbpYAJZZVZuKH6VHftismwacgN57+xceuS+Bokf1VHHU7Fo3oV1+LK2CIm2kTherkdgSlYzcU2bgX9ooaom3MDtJzZrbgswXm/5w/WL2IS8rQVGcfwSMLqamEmDS4ERl0DbhSGroPd/V6Lm1wrp/I0kR1PePjYeRoZr/zbJUg9Hp0h1BYldUZdtsnXxPocg0NVodGR8f5K0YOS3pw81zWciM2bC8YytRv1VAskW9kiQQR58K+IP1+tV1ggzBxQ7x3D1jXV9meKX8m+4LaHxw=
